FROM ubuntu:16.04

RUN apt-get update && apt-get install -y openssh-server sudo vim
RUN mkdir /var/run/sshd
RUN echo 'root:abcd1234' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# Install node 10
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs

# Install bitcoin
RUN apt-get install -y software-properties-common build-essential libtool autotools-dev autoconf libssl-dev libboost-all-dev
RUN add-apt-repository ppa:bitcoin/bitcoin
RUN apt-get update
RUN apt-get -y install bitcoind
RUN mkdir -p $HOME/.bitcoin

# Install lightning
RUN apt-get update
RUN apt-get install -y autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev python python3 net-tools zlib1g-dev libbase58-dev jq python3-mako gettext
RUN cd $HOME && curl -o LATEST.tar.gz "https://download.libsodium.org/libsodium/releases/LATEST.tar.gz" && tar -xvf ./LATEST.tar.gz && cd libsodium-stable && ./configure && make && make check && make install
RUN cd $HOME && git clone https://github.com/ElementsProject/lightning.git && cd lightning && ./configure && make && make install
RUN mkdir -p $HOME/.lightning

# Clone and prepare patching-lightning
RUN cd $HOME && git clone https://github.com/nachikettapas/patching-lightning.git && cd patching-lightning && npm install && cd node_modules/webtorrent/ && rm -r node_modules/ && npm install && export LC_ALL=C && apt install -y python3-pip &&  cd $HOME/patching-lightning/Utils/AddressGeneration/ && pip3 install -r requirements.txt

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]